urdf_path: "./piper.urdf"
srdf_path: "./piper.srdf"
joint_stiffness: 1000
joint_damping: 200
gripper_stiffnes: 1000
gripper_damping: 200
move_group: ["link6","link6"]
ee_joints: ["joint6","joint6"]
arm_joints_name: [['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6'],
                  ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']]
gripper_name: 
  - base: "joint7"
    mimic: [["joint8", 1., 0.]]
  - base: "joint7"
    mimic: [["joint8", 1., 0.]]
gripper_bias: 0.12
gripper_scale: [-0.01, 0.04]
homestate: [[0,0,0,0,0,0],[0,0,0,0,0,0]]
delta_matrix: [[0,0,-1],[0,1,0],[1,0,0]]
global_trans_matrix: [[0,0,1],[0,1,0],[-1,0,0]]
robot_pose: [[0, -0.45, 0.75, 0.707, 0, 0, 0.707]]  # modify
# planner: "mplib_RRT"
planner: "curobo"
dual_arm: False
rotate_lim: [0.2, 1]
grasp_perfect_direction: ['front_right', 'front_left']
static_camera_list: 
- name: head_camera
  position:
  - -0.032
  - -0.45
  - 1.35
  forward:
  - 0
  - 0.6
  - -0.8
  left:
  - -1
  - 0
  - 0
# - name: front_camera
#   type: D435
#   position:
#   - 0
#   - -0.45
#   - 0.85
#   forward:
#   - 0
#   - 1
#   - -0.1
#   left:
#   - -1
#   - 0
#   - 0